### ISSUE TITLE
Generated layout tests fail on Windows

### ISSUE THREAD

**Issue by wingertge** [tracel-ai/cubecl-hip#1]
Bindgen automatically generates layout tests that assume pointer size and other platform specific values. To ensure compatibility with Windows, these tests should be disabled via `--no-layout-tests` on the bindgen command. The specific thing that fails is `c_long`, which assumes `i64` on Linux but `i32` on Windows. This makes the size tests fail.

**Comment by syl20bnr** [comment]
Thank you Genna ! I'll add this soon.
