### ISSUE TITLE
Create different branches for different major/minor version pairs

### ISSUE THREAD

**Issue by VlaDexa** [tracel-ai/cubecl-hip#10]
I assume there's no point in keeping outdated patch versions up to date with latest changes, but, if someone already would've contributed 6.3 bindings, backporting #9 to 6.2 would've been a pain

**Comment by syl20bnr** [comment]
I agree, while `build.rs` is not stable this is not ideal. But it is easy to re-release some binding versions like I did it with `6.2.2001`. There will likely be other re-releases soon while we are stabilizing the build script.

**Comment by syl20bnr** [comment]
Thinking about it, yep, you are right. 

Going to create release branches soon. Bear with me while I am stabilizing this mess 😄
