### ISSUE TITLE
CI checks only one version of the bindings 

### ISSUE THREAD

**Issue by VlaDexa** [tracel-ai/cubecl-hip#4]
If you're planning to maintain bindings for more than one version, this CI configuration won't really work well, because it only checks the version that is configured.

**Comment by syl20bnr** [comment]
Indeed you are right.
To keep things simple and keep the CI as it is I will match the version of the crate with the version with HIP and we put the corresponding HIP version to the default feature. People will be able to downgrade by either ignore the default feature and add an earlier one or just change the crate version.

**Comment by syl20bnr** [comment]
I released the new version scheme and updated the README.
Basically the crate follows the version of the default bindings but the patch version is multiplied by 1000 so it leaves room to make several releases with the same default bindings version.
