### ISSUE TITLE
6.2.2 bindings use version 6.2.4

### ISSUE THREAD

**Issue by VlaDexa** [tracel-ai/cubecl-hip#8]
https://github.com/tracel-ai/cubecl-hip/blob/4721d39a4ef4e13a2ce05e20dcd3e02828520ea3/crates/cubecl-hip-sys/src/bindings/bindings_622.rs#L234-L236

It's the same version as in 6.2.4 bindings

**Comment by syl20bnr** [comment]
I asked why here: https://github.com/ROCm/HIP/issues/3703

Makes sense. I'll likely make some tweaks to take this into account.

**Comment by VlaDexa** [comment]
Why must HIP have a slightly different versioning scheme to ROCm 😭
Is this crate going to follow HIP versioning or rocm?

**Comment by syl20bnr** [comment]
I re-release the previous bindings version `6.2.2` and `6.2.4`, they both use the same version of the HIP bindings.
The latest version `6.3.0` is released as well. This version has updated bindings.
